### PR TITLE
Support for Contao4

### PR DESCRIPTION
**Pull request by Defcon0**
Here you are :-)

### CODE REVIEW

**Comment by aschempp** [comment]
That does not include the necessary backend adjustments (icons etc 😉 )

**Comment by Defcon0** [comment]
Mhm, could you please go more in detail? The plugin works like a charm so far in our Contao 4.3 and also 4.4 instance. In 4.4 we don't have the icons from the backend modules in the left nav bar anymore. So which icons don't work?

**Comment by aschempp** [comment]
You're right, the icons were only for the backend. Still I updated to code to work with PHP7 as well

**Comment by Defcon0** [comment]
Great, thanks ;-)

**Pull request merged**
